[package]
name = "spongy"
version = "0.2.0"
authors = ["heyrict <xiezh0831@yahoo.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
